# Generated by Django 4.2.16 on 2025-01-07 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0004_remove_order_remark_order_buyer_remark_and_more'),
        ('storage', '0002_stockin_unit_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh', models.CharField(max_length=25, verbose_name='中文名称')),
                ('name_en', models.CharField(max_length=25, verbose_name='英文名称')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='物流商代码')),
                ('url', models.URLField(blank=True, verbose_name='官网地址')),
                ('contact', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('query_key', models.IntegerField(blank=True, null=True, verbose_name='查询代码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '物流商',
                'verbose_name_plural': '物流商',
                'db_table': 'logistics_carrier',
                'ordering': ['name_zh'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='跟踪号')),
                ('pkg_status_code', models.CharField(choices=[('0', '待发货'), ('1', '待揽收'), ('2', '转运中'), ('3', '已签收'), ('4', '已取消')], default='0', max_length=4, verbose_name='包裹状态码')),
                ('items', models.JSONField(help_text='包含SKU、品名、包裹尺寸、重量等信息', verbose_name='商品列表')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='长(cm)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='宽(cm)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='高(cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='重量(kg)')),
                ('estimated_logistics_cost', models.DecimalField(decimal_places=2, default=0, help_text='系统计算的预估物流费用', max_digits=10, verbose_name='预估物流费用')),
                ('carrier_cost', models.DecimalField(blank=True, decimal_places=2, help_text='物流商回传的实际费用', max_digits=10, null=True, verbose_name='物流商费用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='trade.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '包裹',
                'verbose_name_plural': '包裹',
                'db_table': 'logistics_package',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '待发货'), (1, '待揽收'), (2, '转运中'), (3, '已签收'), (4, '已取消')], default=0, verbose_name='物流状态')),
                ('location', models.CharField(max_length=100, verbose_name='当前位置')),
                ('description', models.CharField(max_length=200, verbose_name='轨迹描述')),
                ('tracking_time', models.DateTimeField(verbose_name='轨迹时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='logistics.package', verbose_name='包裹')),
            ],
            options={
                'verbose_name': '物流轨迹',
                'verbose_name_plural': '物流轨迹',
                'db_table': 'logistics_tracking',
                'ordering': ['-tracking_time'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=25, verbose_name='服务名称')),
                ('service_code', models.CharField(max_length=10, verbose_name='服务代码')),
                ('service_type', models.IntegerField(verbose_name='服务类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='logistics.carrier', verbose_name='物流商')),
            ],
            options={
                'verbose_name': '物流服务',
                'verbose_name_plural': '物流服务',
                'db_table': 'logistics_service',
                'ordering': ['carrier', 'service_name'],
                'unique_together': {('carrier', 'service_code')},
            },
        ),
        migrations.AddField(
            model_name='package',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='logistics.service', verbose_name='物流服务'),
        ),
        migrations.AddField(
            model_name='package',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.warehouse', verbose_name='发货仓库'),
        ),
    ]
