# Generated by Django 4.2.16 on 2025-01-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_package_pkg_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='pkg_status_code',
            field=models.CharField(choices=[('0', '待发货'), ('1', '待揽收'), ('2', '转运中'), ('3', '已签收'), ('4', '已取消')], default='0', max_length=4, verbose_name='包裹状态码'),
        ),
    ]
