# Generated by Django 4.2.16 on 2025-01-06 17:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True, verbose_name='批次编号')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='剩余数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='gallery.sku', verbose_name='商品SKU')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存列表',
                'db_table': 'storage_inventory',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(max_length=50, unique=True, verbose_name='仓库编码')),
                ('warehouse_name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('location', models.CharField(max_length=200, verbose_name='仓库地址')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='仓库管理员')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库列表',
                'db_table': 'storage_warehouse',
                'ordering': ['warehouse_code'],
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_out_code', models.CharField(max_length=50, unique=True, verbose_name='出库单号')),
                ('stock_out_type', models.CharField(choices=[('sales', '销售出库'), ('return', '退货出库'), ('transfer', '调拨出库')], max_length=20, verbose_name='出库类型')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='出库数量')),
                ('related_order', models.CharField(blank=True, max_length=50, null=True, verbose_name='关联单号')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('stock_out_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='出库时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_outs', to='storage.inventory', verbose_name='库存批次')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operated_stock_outs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_outs', to='gallery.sku', verbose_name='商品SKU')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_outs', to='storage.warehouse', verbose_name='出库仓库')),
            ],
            options={
                'verbose_name': '出库记录',
                'verbose_name_plural': '出库记录列表',
                'db_table': 'storage_stock_out',
                'ordering': ['-stock_out_time'],
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_in_code', models.CharField(max_length=50, unique=True, verbose_name='入库单号')),
                ('stock_in_type', models.CharField(choices=[('purchase', '采购入库'), ('return', '退货入库'), ('transfer', '调拨入库')], max_length=20, verbose_name='入库类型')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='入库数量')),
                ('source_order', models.CharField(blank=True, max_length=50, null=True, verbose_name='来源单号')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('stock_in_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='入库时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock_in', to='storage.inventory', verbose_name='库存批次')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operated_stock_ins', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ins', to='gallery.sku', verbose_name='商品SKU')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ins', to='storage.warehouse', verbose_name='入库仓库')),
            ],
            options={
                'verbose_name': '入库记录',
                'verbose_name_plural': '入库记录列表',
                'db_table': 'storage_stock_in',
                'ordering': ['-stock_in_time'],
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='storage.warehouse', verbose_name='所属仓库'),
        ),
    ]
