# Generated by Django 4.2.16 on 2025-01-09 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_stockin_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='low_stock_threshold',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='低库存阈值'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='入库时的单位成本金额', max_digits=10, verbose_name='单位成本'),
        ),
    ]
