# Generated by Django 4.2.16 on 2025-01-06 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品牌名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='品牌描述')),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='logoURL')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌列表',
                'db_table': 'gallery_brand',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='分类ID')),
                ('category_name_en', models.CharField(max_length=100, verbose_name='英文名称')),
                ('category_name_zh', models.CharField(max_length=100, verbose_name='中文名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to=gallery.models.category_image_path, verbose_name='分类图片')),
                ('rank_id', models.IntegerField(default=0, verbose_name='排序ID')),
                ('original_data', models.TextField(blank=True, null=True, verbose_name='原始数据')),
                ('level', models.IntegerField(choices=[(1, '一级分类'), (2, '二级分类'), (3, '三级分类'), (4, '四级分类'), (5, '五级分类'), (6, '六级分类'), (7, '七级分类')], default=1, verbose_name='分类层级')),
                ('is_last_level', models.BooleanField(default=False, verbose_name='是否最后一级')),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gallery.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'gallery_category',
                'ordering': ['rank_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spu_code', models.CharField(max_length=50, unique=True, verbose_name='SPU编码')),
                ('spu_name', models.CharField(max_length=100, verbose_name='SPU名称')),
                ('product_type', models.CharField(choices=[('math_design', '设计款'), ('ready_made', '现货款'), ('raw_material', '材料'), ('packing_material', '包材')], max_length=20, verbose_name='产品类型')),
                ('spu_remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('sales_channel', models.CharField(blank=True, max_length=20, null=True, verbose_name='销售渠道')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.brand', verbose_name='品牌')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.category', verbose_name='类目')),
                ('poc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='专员')),
            ],
            options={
                'verbose_name': 'SPU',
                'verbose_name_plural': 'SPU列表',
                'db_table': 'gallery_spu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=50, unique=True, verbose_name='SKU编码')),
                ('sku_name', models.CharField(max_length=100, verbose_name='SKU名称')),
                ('material', models.CharField(max_length=50, verbose_name='材质')),
                ('color', models.CharField(max_length=50, verbose_name='颜色')),
                ('plating_process', models.CharField(choices=[('none', '无电镀'), ('gold', '镀金'), ('silver', '镀银'), ('nickel', '镀镍'), ('chrome', '镀铬'), ('copper', '镀铜'), ('other', '其他')], max_length=20, verbose_name='电镀工艺')),
                ('surface_treatment', models.CharField(blank=True, max_length=100, null=True, verbose_name='表面处理')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='重量(g)')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='长(mm)')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='宽(mm)')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='高(mm)')),
                ('other_dimensions', models.CharField(blank=True, max_length=25, null=True, verbose_name='其他尺寸')),
                ('suppliers_list', models.TextField(blank=True, default='[]', verbose_name='供应商列表')),
                ('img_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片URL')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('spu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.spu', verbose_name='所属SPU')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU列表',
                'db_table': 'gallery_sku',
                'ordering': ['-created_at'],
            },
        ),
    ]
