# Generated by Django 4.2.16 on 2025-01-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='是否已审核'),
        ),
    ]
