# Generated by Django 4.2.16 on 2025-01-07 13:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店铺名称')),
                ('platform', models.CharField(choices=[('shopify', 'Shopify'), ('tiktok', 'Tik Tok'), ('etsy', 'Etsy'), ('offline', '线下订单')], max_length=20, verbose_name='所属平台')),
                ('shop_code', models.CharField(max_length=50, unique=True, verbose_name='店铺编号')),
                ('status', models.IntegerField(choices=[(1, '正常'), (0, '停用')], default=1, verbose_name='状态')),
                ('description', models.TextField(blank=True, null=True, verbose_name='店铺描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_shops', to=settings.AUTH_USER_MODEL, verbose_name='店铺管理员')),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺列表',
                'db_table': 'trade_shop',
                'ordering': ['platform', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('platform_order_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='平台订单号')),
                ('order_type', models.CharField(choices=[('normal', '普通订单'), ('wholesale', '批发订单'), ('sample', '样品订单'), ('replacement', '补发订单'), ('return', '退换货订单')], default='normal', max_length=20, verbose_name='订单类型')),
                ('package_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='包裹ID')),
                ('status', models.CharField(choices=[('unpaid', '未支付'), ('pending', '待处理'), ('picking', '配货中'), ('shipped', '已发货'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='订单总金额')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='物流运费')),
                ('payment_method', models.CharField(choices=[('online', '在线支付'), ('bank_transfer', '银行转账')], max_length=20, verbose_name='支付方式')),
                ('payment_status', models.BooleanField(default=False, verbose_name='支付状态')),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('shipping_address', models.TextField(verbose_name='收货地址')),
                ('shipping_contact', models.CharField(max_length=50, verbose_name='收货人')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='邮编')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='订单备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trade.shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单列表',
                'db_table': 'trade_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='单价')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='折扣(%)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='小计金额')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trade.order', verbose_name='所属订单')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='gallery.sku', verbose_name='商品SKU')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品列表',
                'db_table': 'trade_cart',
            },
        ),
    ]
