# Generated by Django 4.2.16 on 2025-01-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('platform', '平台订单'), ('influencer', '达人订单'), ('offline', '线下订单'), ('requisition', '员工领用'), ('employee', '员工自购')], default='normal', max_length=20, verbose_name='订单类型'),
        ),
    ]
