# Generated by Django 4.2.16 on 2025-01-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_place_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下单时间'),
        ),
    ]
