# Generated by Django 4.2.16 on 2025-01-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_order_order_place_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='remark',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_remark',
            field=models.TextField(blank=True, default='', verbose_name='买家备注'),
        ),
        migrations.AddField(
            model_name='order',
            name='cs_remark',
            field=models.TextField(blank=True, default='', verbose_name='客服备注'),
        ),
        migrations.AddField(
            model_name='order',
            name='system_remark',
            field=models.TextField(blank=True, default='', verbose_name='系统备注'),
        ),
    ]
