# Generated by Django 4.2.16 on 2025-01-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_remove_order_remark_order_buyer_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('CNY', '人民币'), ('USD', '美元'), ('EUR', '欧元'), ('GBP', '英镑')], default='CNY', max_length=3, verbose_name='币种'),
        ),
    ]
