# Generated by Django 4.2.16 on 2025-01-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_order_city_order_country_order_district_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exchange_rate_to_usd',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='美元汇率'),
        ),
    ]
