# Generated by Django 4.2.16 on 2025-01-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_remove_demandrequest_requester_demandrequest_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandrequest',
            name='sku',
        ),
    ]
