# Generated by Django 4.2.16 on 2025-01-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下单时间'),
        ),
    ]
