# Generated by Django 4.2.16 on 2025-01-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_purchaseorder_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='仓库ID'),
        ),
    ]
